include makeEspArduino.mk

trace:
	echo java -jar EspStackTraceDecoder.jar /home/danny/src/github/esp8266/esp8266-2.7.4/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-addr2line buildroot/measure_d1_mini/measure.elf x
	echo java -jar EspStackTraceDecoder.jar 
	echo ${COMP_PATH}
	echo ${CPP_COM_PREFIX}
