include makeEspArduino.mk

trace:
	java -jar EspStackTraceDecoder.jar /home/danny/src/github/esp8266/esp8266-2.7.4/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-addr2line buildroot/measure_d1_mini/measure.elf x

tools:
	ln -s /home/danny/src/github/makeEspArduino/tools .
